import os
import json
import time
import pandas as pd
from pathlib import Path
from dotenv import load_dotenv
from google import genai
from google.genai import types

load_dotenv()

PROJECT_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = PROJECT_ROOT / "output"

def load_feedback(vid: str):
    """Load feedback JSONs from the 3 approaches for a given video."""
    paths = {
        "Approach_1_Rule": OUTPUT_DIR / "feedback" / f"{vid}_feedback.json",
        "Approach_2_MLLM": OUTPUT_DIR / "feedback_mllm" / f"{vid}_feedback.json",
        "Approach_3_Hybrid": OUTPUT_DIR / "feedback_hybrid" / f"{vid}_feedback.json"
    }
    
    feedbacks = {}
    for name, p in paths.items():
        if p.exists():
            with open(p, "r", encoding="utf-8") as f:
                feedbacks[name] = json.load(f)
        else:
            feedbacks[name] = None
            print(f"Warning: {p.name} not found for {name}.")
    return feedbacks

def judge_feedback(client, vid: str, feedbacks: dict):
    """Use LLM-as-a-Judge to evaluate the feedback quality of the 3 approaches."""
    
    # We only include approaches that have feedback
    feedback_text = ""
    for name, data in feedbacks.items():
        if data:
            feedback_text += f"=== {name} ===\n{json.dumps(data, ensure_ascii=False, indent=2)}\n\n"
            
    if not feedback_text:
        return None

    prompt = f"""You are an expert interview coach and an AI evaluator.
Your task is to evaluate the quality of feedback generated by different AI systems for the same candidate video ({vid}).

Here is the feedback generated by the approaches:
{feedback_text}

Evaluate EACH approach on a scale of 1 to 10 for the following criteria:
1. Specificity: How detailed and specific to the candidate's actual performance is the feedback? (Avoids generic platitudes).
2. Actionability: How clear and practical are the improvement steps? Can the candidate easily follow them?
3. Empathy: Is the tone encouraging, professional, and supportive?
4. Overall Quality: Holistic score of the feedback's value to the candidate.

Output MUST be a JSON object with this exact structure:
{{
  "Approach_1_Rule": {{ "Specificity": 0, "Actionability": 0, "Empathy": 0, "Overall": 0, "Reasoning": "" }},
  "Approach_2_MLLM": {{ "Specificity": 0, "Actionability": 0, "Empathy": 0, "Overall": 0, "Reasoning": "" }},
  "Approach_3_Hybrid": {{ "Specificity": 0, "Actionability": 0, "Empathy": 0, "Overall": 0, "Reasoning": "" }}
}}
If an approach is missing from the input, omit it from the JSON.
"""

    print(f"Evaluating {vid}...")
    retries = 5
    backoff = [10, 20, 40, 60, 90]
    
    for attempt in range(retries):
        try:
            response = client.models.generate_content(
                model="gemini-3.8-flash",
                contents=[prompt],
                config=types.GenerateContentConfig(
                    response_mime_type="application/json",
                    temperature=0.2,
                )
            )
            return json.loads(response.text)
        except Exception as e:
            err_str = str(e)
            if attempt < retries - 1:
                wait = backoff[attempt] if attempt < len(backoff) else 60
                print(f"       [RETRY] API error: {err_str[:80]} - waiting {wait}s...")
                time.sleep(wait)
            else:
                print(f"Error evaluating {vid} after {retries} retries: {e}")
                return None

def main():
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        print("Error: GEMINI_API_KEY not found in .env")
        return
        
    client = genai.Client(api_key=api_key)
    
    # Find all videos that have at least some feedback
    vids = set()
    for subdir in ["feedback", "feedback_mllm", "feedback_hybrid"]:
        d = OUTPUT_DIR / subdir
        if d.exists():
            for f in d.glob("*_feedback.json"):
                vid = f.name.replace("_feedback.json", "")
                vids.add(vid)
                
    if not vids:
        print("No feedback files found in output directory.")
        return
        
    print(f"Found {len(vids)} videos to evaluate: {', '.join(vids)}")
    
    all_results = []
    
    for vid in sorted(vids):
        feedbacks = load_feedback(vid)
        evaluation = judge_feedback(client, vid, feedbacks)
        
        if evaluation:
            for approach, scores in evaluation.items():
                row = {
                    "Video_ID": vid,
                    "Approach": approach,
                    "Specificity": scores.get("Specificity", 0),
                    "Actionability": scores.get("Actionability", 0),
                    "Empathy": scores.get("Empathy", 0),
                    "Overall": scores.get("Overall", 0),
                    "Reasoning": scores.get("Reasoning", "")
                }
                all_results.append(row)
                
        time.sleep(2) # rate limiting
        
    if all_results:
        df = pd.DataFrame(all_results)
        
        # Calculate averages per approach
        avg_scores = df.groupby("Approach")[["Specificity", "Actionability", "Empathy", "Overall"]].mean().reset_index()
        
        print("\n" + "="*60)
        print("FEEDBACK QUALITY COMPARISON (LLM-as-a-Judge)")
        print("="*60)
        print(avg_scores.to_string(index=False))
        print("="*60)
        
        # Save results
        report_dir = PROJECT_ROOT / "report"
        report_dir.mkdir(exist_ok=True)
        csv_path = report_dir / "approach_comparison_metrics.csv"
        df.to_csv(csv_path, index=False)
        print(f"Detailed evaluation saved to {csv_path.relative_to(PROJECT_ROOT)}")
        
if __name__ == "__main__":
    main()
